services:
  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jonas
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
